config/routes.rb
Tasks::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :users
  end

end

ActionDispatch::Routing::Translator.translate_from_file(
    "config/locales/routes.yml", {
    keep_untranslated_routes: true,
    :no_prefixes => true })

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :cpf

  validates :name, :cpf, presence: true
  validates :cpf, uniqueness: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def t_field(model,field)
    t("activerecord.attributes.#{model}.#{field}")
  end
end

app/views/admin/users/_user.html.erb
<tr class="user" id="<%= dom_id(user) %>">
  <td><%= link_to user.id, admin_user_path(user) %></td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%=l user.created_at %></td>
  <td>
    <%= link_to t("helpers.actions.show"),
                admin_user_path(user), :class => 'btn btn-mini' %>
    <%= link_to t("helpers.actions.edit"),
                edit_admin_user_path(user), :class => 'btn btn-info btn-mini' %>
    <%= link_to t("helpers.actions.destroy"),
                admin_user_path(user), method: :delete, confirm: t('helpers.actions.confirm'), :class => 'btn btn-danger btn-mini' %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<%= provide(:title,  t('titles.admin.users.index')) %>
<%= provide :breadcrumb do %>
    <li class="active"><%= t('shared.admin.nav.users') %></li>
<% end %>

<div class="page-header">
  <h2><%=  t('titles.admin.users.index') %></h2>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Id</th>
    <th><%= t_field('user','name') %></th>
    <th><%= t_field('user','email') %></th>
    <th><%= t('helpers.created_at') %></th>
    <th><%=t 'helpers.actions.all' %></th>
  </tr>
  </thead>
  <tbody>
  <%= render @users %>
  </tbody>
</table>
<%= paginate @users %>
<%= link_to t("helpers.actions.new"),
            new_admin_user_path,
            :class => 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tasks" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Tasks</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <ul class="breadcrumb">
          <li><a href="/"><%= t('shared.admin.home') %></a> <span class="divider">/</span></li>
            <%= yield :breadcrumb %>
          </ul>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>